### ISSUE TITLE
Port to Magisk

### ISSUE THREAD

**Issue by DonCorleone94** [apsun/TumblrAdAway#10]
Hello, there is a possibility to port the module to Magisk?

**Comment by apsun** [comment]
I have never used Magisk (truth be told I don't even run Xposed on my main phone anymore), so unfortunately I have no idea. Correct me if I'm wrong, but I thought Magisk was a way to modify the filesystem in memory without touching any files on disk? In that case, Xposed would still be necessary, since that is what actually allows code injection.

**Comment by DonCorleone94** [comment]
yes I think so. It probably will not be without Xposed. thanks for the answer. Regards
