### ISSUE TITLE
Not working on Xposed Tumblr 5.6.x

### ISSUE THREAD

**Issue by thankfulfornever** [apsun/TumblrAdAway#2]
Any updates to this?

**Comment by apsun** [comment]
I actually haven't received the update yet (I'm still on 5.5). I'll let you know when Google Play decides to push it out to my phone.

**Comment by apsun** [comment]
I've updated to 5.6.1, and it seems to work fine. Can you post a logcat output?

`adb logcat -s "TumblrAdAway"`

**Comment by thankfulfornever** [comment]
It isn't showing up yet in my Xposed updates. I'll let you know when it
does.

**Comment by apsun** [comment]
Oh, I meant the Tumblr app, I haven't updated the Xposed module in a while now (because the way ads are loaded hasn't changed since 5.1.0).

**Comment by thankfulfornever** [comment]
Oh ok. I'm running Xposed on 5.6.x and the ads are showing up, but maybe
I'm doing something wrong.

**Comment by apsun** [comment]
It's working fine on my end, so I can't diagnose the problem without any logs. Could you post your Xposed logs? (Xposed Installer -> Logs -> Menu -> Send/Save to SD card)

**Comment by thankfulfornever** [comment]
Attached

**Comment by apsun** [comment]
Hmm, I can't see it, I guess email reply doesn't handle attachments... Could you paste it as a code block using the website instead?

**Comment by LendingMemo** [comment]
03-22 00:50:18.615 I/Xposed  (  497): -----------------
03-22 00:50:18.615 I/Xposed  (  497): Starting Xposed version 79, compiled for SDK 23
03-22 00:50:18.615 I/Xposed  (  497): Device: LG-D850 (LGE), Android version 6.0 (SDK 23)
03-22 00:50:18.615 I/Xposed  (  497): ROM: MRA58K
03-22 00:50:18.615 I/Xposed  (  497): Build fingerprint: lge/g3_global_com/g3:6.0/MRA58K/15351124649f4:user/release-keys
03-22 00:50:18.615 I/Xposed  (  497): Platform: armeabi-v7a, 32-bit binary, system server: yes
03-22 00:50:18.615 I/Xposed  (  497): SELinux enabled: yes, enforcing: no
03-22 00:50:20.839 I/Xposed  (  497): -----------------
03-22 00:50:20.840 I/Xposed  (  497): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
03-22 00:50:21.055 I/Xposed  (  497): Detected ART runtime
03-22 00:50:21.083 I/Xposed  (  497): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
03-22 00:50:21.344 I/Xposed  (  497): Loading modules from /data/app/com.Taptigo.XposedModules.IgZoom-1/base.apk
03-22 00:50:21.500 I/Xposed  (  497):   Loading class com.Taptigo.XposedModules.IgZoom.RootHook
03-22 00:50:21.526 I/Xposed  (  497): Loading modules from /data/app/com.jt5.xposed.chromepie-1/base.apk
03-22 00:50:21.565 I/Xposed  (  497):   Loading class com.jt5.xposed.chromepie.ChromePie
03-22 00:50:21.575 I/Xposed  (  497): Loading modules from /data/app/com.marz.snapprefs-1/base.apk
03-22 00:50:21.661 I/Xposed  (  497):   Loading class com.marz.snapprefs.HookMethods
03-22 00:50:21.695 I/Xposed  (  497): Loading modules from /data/app/ma.wanam.youtubeadaway-1/base.apk
03-22 00:50:21.711 I/Xposed  (  497):   Loading class ma.wanam.youtubeadaway.Xposed
03-22 00:50:21.713 I/Xposed  (  497): Loading modules from /data/app/com.bocharov.xposed.fskeyboard-2/base.apk
03-22 00:50:21.761 I/Xposed  (  497):   Loading class com.bocharov.xposed.fskeyboard.Module
03-22 00:50:21.780 I/Xposed  (  497): Loading modules from /data/app/com.tonymanou.screenfilter-1/base.apk
03-22 00:50:21.803 I/Xposed  (  497):   Loading class com.tonymanou.screenfilter.FilterXposed
03-22 00:50:32.221 I/Xposed  ( 3378): Screen Filter: registering service on SDK 23...
03-22 00:50:32.223 I/Xposed  ( 3378): Screen Filter: service successfully registered (1.5.2)
03-22 00:50:35.942 I/Xposed  ( 4653): Screen Filter: com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView()
03-22 00:50:35.996 I/Xposed  ( 4653): Screen Filter: overlay successfully added
03-22 00:51:07.821 E/Xposed  ( 9674): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.google.android.libraries.youtube.innertube.model.ads.VastAd
03-22 00:51:07.821 E/Xposed  ( 9674): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:54)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at ma.wanam.youtubeadaway.XYoutube.doHook(Unknown Source)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at ma.wanam.youtubeadaway.Xposed.handleLoadPackage(Unknown Source)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:173)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:655)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at android.app.ActivityThread.access$1600(ActivityThread.java:157)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at android.os.Looper.loop(Looper.java:148)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at android.app.ActivityThread.main(ActivityThread.java:5527)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at java.lang.reflect.Method.invoke(Native Method)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
03-22 00:51:07.821 E/Xposed  ( 9674): Caused by: java.lang.ClassNotFoundException: com.google.android.libraries.youtube.innertube.model.ads.VastAd
03-22 00:51:07.821 E/Xposed  ( 9674): 	at java.lang.Class.classForName(Native Method)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at java.lang.Class.forName(Class.java:324)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
03-22 00:51:07.821 E/Xposed  ( 9674): 	... 17 more
03-22 00:51:07.821 E/Xposed  ( 9674): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.libraries.youtube.innertube.model.ads.VastAd" on path: DexPathList[[zip file "/data/app/com.google.android.youtube-2/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.youtube-2/lib/arm, /data/app/com.google.android.youtube-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
03-22 00:51:07.821 E/Xposed  ( 9674): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
03-22 00:51:07.821 E/Xposed  ( 9674): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
03-22 00:51:07.821 E/Xposed  ( 9674): 	... 21 more
03-22 00:51:07.821 E/Xposed  ( 9674): 	Suppressed: java.lang.ClassNotFoundException: com.google.android.libraries.youtube.innertube.model.ads.VastAd
03-22 00:51:07.821 E/Xposed  ( 9674): 		at java.lang.Class.classForName(Native Method)
03-22 00:51:07.821 E/Xposed  ( 9674): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
03-22 00:51:07.821 E/Xposed  ( 9674): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
03-22 00:51:07.821 E/Xposed  ( 9674): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
03-22 00:51:07.821 E/Xposed  ( 9674): 		... 22 more
03-22 00:51:07.821 E/Xposed  ( 9674): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
03-22 00:51:07.821 I/Xposed  ( 9674): Trying brute force way...
03-22 00:51:07.948 I/Xposed  ( 9674): Succes hook for sequence: class =lvo param=jrp for YouTube 11.07.59
03-22 00:51:09.990 I/Xposed  ( 9856): [Taptigo-XposedZoomForInstagram] Hooking Instagram
03-22 00:51:11.669 I/Xposed  ( 9908): [Taptigo-XposedZoomForInstagram] Hooking Instagram
03-22 02:27:12.762 I/Xposed  (25909): [Taptigo-XposedZoomForInstagram] Hooking Instagram
03-22 08:17:43.687 E/Xposed  (13486): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.google.android.libraries.youtube.innertube.model.ads.VastAd
03-22 08:17:43.687 E/Xposed  (13486): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:54)
03-22 08:17:43.687 E/Xposed  (13486): 	at ma.wanam.youtubeadaway.XYoutube.doHook(Unknown Source)
03-22 08:17:43.687 E/Xposed  (13486): 	at ma.wanam.youtubeadaway.Xposed.handleLoadPackage(Unknown Source)
03-22 08:17:43.687 E/Xposed  (13486): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
03-22 08:17:43.687 E/Xposed  (13486): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
03-22 08:17:43.687 E/Xposed  (13486): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
03-22 08:17:43.687 E/Xposed  (13486): 	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:173)
03-22 08:17:43.687 E/Xposed  (13486): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:655)
03-22 08:17:43.687 E/Xposed  (13486): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
03-22 08:17:43.687 E/Xposed  (13486): 	at android.app.ActivityThread.access$1600(ActivityThread.java:157)
03-22 08:17:43.687 E/Xposed  (13486): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
03-22 08:17:43.687 E/Xposed  (13486): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-22 08:17:43.687 E/Xposed  (13486): 	at android.os.Looper.loop(Looper.java:148)
03-22 08:17:43.687 E/Xposed  (13486): 	at android.app.ActivityThread.main(ActivityThread.java:5527)
03-22 08:17:43.687 E/Xposed  (13486): 	at java.lang.reflect.Method.invoke(Native Method)
03-22 08:17:43.687 E/Xposed  (13486): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
03-22 08:17:43.687 E/Xposed  (13486): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
03-22 08:17:43.687 E/Xposed  (13486): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
03-22 08:17:43.687 E/Xposed  (13486): Caused by: java.lang.ClassNotFoundException: com.google.android.libraries.youtube.innertube.model.ads.VastAd
03-22 08:17:43.687 E/Xposed  (13486): 	at java.lang.Class.classForName(Native Method)
03-22 08:17:43.687 E/Xposed  (13486): 	at java.lang.Class.forName(Class.java:324)
03-22 08:17:43.687 E/Xposed  (13486): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
03-22 08:17:43.687 E/Xposed  (13486): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
03-22 08:17:43.687 E/Xposed  (13486): 	... 17 more
03-22 08:17:43.687 E/Xposed  (13486): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.libraries.youtube.innertube.model.ads.VastAd" on path: DexPathList[[zip file "/data/app/com.google.android.youtube-2/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.youtube-2/lib/arm, /data/app/com.google.android.youtube-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
03-22 08:17:43.687 E/Xposed  (13486): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-22 08:17:43.687 E/Xposed  (13486): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
03-22 08:17:43.687 E/Xposed  (13486): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
03-22 08:17:43.687 E/Xposed  (13486): 	... 21 more
03-22 08:17:43.687 E/Xposed  (13486): 	Suppressed: java.lang.ClassNotFoundException: com.google.android.libraries.youtube.innertube.model.ads.VastAd
03-22 08:17:43.687 E/Xposed  (13486): 		at java.lang.Class.classForName(Native Method)
03-22 08:17:43.687 E/Xposed  (13486): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
03-22 08:17:43.687 E/Xposed  (13486): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
03-22 08:17:43.687 E/Xposed  (13486): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
03-22 08:17:43.687 E/Xposed  (13486): 		... 22 more
03-22 08:17:43.687 E/Xposed  (13486): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
03-22 08:17:43.687 I/Xposed  (13486): Trying brute force way...
03-22 08:17:43.831 I/Xposed  (13486): Succes hook for sequence: class =lvo param=jrp for YouTube 11.07.59
03-22 10:03:48.898 I/Xposed  (21089): [Taptigo-XposedZoomForInstagram] Hooking Instagram
03-22 11:02:12.684 I/Xposed  (21089): [Taptigo-XposedZoomForInstagram] com.instagram.android.activity.MainTabActivity.onCreate called
03-22 11:02:13.010 I/Xposed  (21089): [Taptigo-XposedZoomForInstagram] com.instagram.android.activity.MainTabActivity.onResume called
03-22 11:50:57.355 I/XposedInstaller( 1188): Downloaded http://dl.xposed.info/repo/full.xml.gz with status 0 (error: null), size 948028 bytes
03-22 11:51:00.395 I/XposedInstaller( 1188): Updated repository http://dl.xposed.info/repo/full.xml.gz to version 7649 (840 new / 0 removed modules)
03-22 11:51:09.164 I/XposedInstaller( 1188): Downloaded http://dl.xposed.info/repo/partial/7649.xml.gz with status 0 (error: null), size 65 bytes
03-22 11:51:09.167 I/XposedInstaller( 1188): Updated repository http://dl.xposed.info/repo/full.xml.gz to version 7649 (0 new / 0 removed modules)

**Comment by apsun** [comment]
Hmm, it seems that Xposed is not even trying to load TumblrAdAway. Are you sure it's enabled? Try reinstalling it, just in case.

**Comment by thankfulfornever** [comment]
Ack! Wow. I'm dumb. :)

**Comment by apsun** [comment]
Haha, I presume everything is working as expected then? ;-)

**Comment by thankfulfornever** [comment]
Yes :)
